In [19]:
from tensorflow.keras.preprocessing.text import one_hot

In [20]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
## Define the vocabulary size
voc_size=10000

In [22]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3704, 3582, 3220, 5114],
 [3704, 3582, 3220, 8282],
 [3704, 4487, 3220, 9635],
 [6049, 7075, 6284, 4055, 8349],
 [6049, 7075, 6284, 4055, 4967],
 [5232, 3704, 3897, 3220, 825],
 [1403, 6974, 1625, 4055]]

In [23]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [24]:
import numpy as np

In [25]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3704 3582 3220 5114]
 [   0    0    0    0 3704 3582 3220 8282]
 [   0    0    0    0 3704 4487 3220 9635]
 [   0    0    0 6049 7075 6284 4055 8349]
 [   0    0    0 6049 7075 6284 4055 4967]
 [   0    0    0 5232 3704 3897 3220  825]
 [   0    0    0    0 1403 6974 1625 4055]]


In [26]:
## feature representation
dim=10


In [27]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [28]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 287ms/step


array([[[ 2.86839902e-04, -4.06522676e-03, -3.92415896e-02,
         -7.52471760e-03,  4.81951237e-03,  4.81047146e-02,
         -1.88695546e-02,  1.52851455e-02, -1.39684081e-02,
          2.20466591e-02],
        [ 2.86839902e-04, -4.06522676e-03, -3.92415896e-02,
         -7.52471760e-03,  4.81951237e-03,  4.81047146e-02,
         -1.88695546e-02,  1.52851455e-02, -1.39684081e-02,
          2.20466591e-02],
        [ 2.86839902e-04, -4.06522676e-03, -3.92415896e-02,
         -7.52471760e-03,  4.81951237e-03,  4.81047146e-02,
         -1.88695546e-02,  1.52851455e-02, -1.39684081e-02,
          2.20466591e-02],
        [ 2.86839902e-04, -4.06522676e-03, -3.92415896e-02,
         -7.52471760e-03,  4.81951237e-03,  4.81047146e-02,
         -1.88695546e-02,  1.52851455e-02, -1.39684081e-02,
          2.20466591e-02],
        [-3.14048529e-02, -1.62185654e-02,  4.60815094e-02,
         -1.31725147e-03, -1.06474981e-02,  3.41444872e-02,
         -3.75235677e-02, -4.66526523e-02,  1.974782

In [30]:
embedded_docs[0]

array([   0,    0,    0,    0, 3704, 3582, 3220, 5114], dtype=int32)

In [35]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step


array([[[ 2.86839902e-04, -4.06522676e-03, -3.92415896e-02,
         -7.52471760e-03,  4.81951237e-03,  4.81047146e-02,
         -1.88695546e-02,  1.52851455e-02, -1.39684081e-02,
          2.20466591e-02],
        [ 2.86839902e-04, -4.06522676e-03, -3.92415896e-02,
         -7.52471760e-03,  4.81951237e-03,  4.81047146e-02,
         -1.88695546e-02,  1.52851455e-02, -1.39684081e-02,
          2.20466591e-02],
        [ 2.86839902e-04, -4.06522676e-03, -3.92415896e-02,
         -7.52471760e-03,  4.81951237e-03,  4.81047146e-02,
         -1.88695546e-02,  1.52851455e-02, -1.39684081e-02,
          2.20466591e-02],
        [ 2.86839902e-04, -4.06522676e-03, -3.92415896e-02,
         -7.52471760e-03,  4.81951237e-03,  4.81047146e-02,
         -1.88695546e-02,  1.52851455e-02, -1.39684081e-02,
          2.20466591e-02],
        [-3.14048529e-02, -1.62185654e-02,  4.60815094e-02,
         -1.31725147e-03, -1.06474981e-02,  3.41444872e-02,
         -3.75235677e-02, -4.66526523e-02,  1.974782